version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
      time: '14:30'
    patterns:
      - 'org.apache.kafka*'
    registries:
      - maven-central

  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
      time: '14:30'
    open-pull-requests-limit: 20
    exclude-patterns:
      - 'org.apache.kafka*'
