apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: lps-oppfolgingsplan-mottak
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          delegationSource: altinn
          enabled: true
          product: oppfolgingsplan
          separator: "/"
          name: lps.write
          atMaxAge: 680
      consumes:
        - name: "nav:oppfolgingsplan/lps.write"
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  gcp:
    sqlInstances:
      - autoBackupHour: 1
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: GCP_DB
            name: lps-db
        diskAutoresize: true
        diskSize: 12
        diskType: SSD
        highAvailability: false
        insights:
          enabled: true
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        name: lps-instance
        tier: db-f1-micro
        type: POSTGRES_15
  prometheus:
    enabled: true
    path: /prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: oppfolgingsplan-lps-demo
        - application: syfomodiaperson
          namespace: teamsykefravr
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: syfooppdfgen.intern.dev.nav.no
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: ereg-services-q1.dev-fss-pub.nais.io
        - host: aareg-services-q2.dev-fss-pub.nais.io
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: syfooppdfgen
        - application: isdialogmelding
          namespace: teamsykefravr
        - application: istilgangskontroll
          namespace: teamsykefravr
  ingresses:
    - "https://lps-oppfolgingsplan-mottak.ekstern.dev.nav.no"
  filesFrom:
    - secret: lps-oppfolgingsplan-mottak-secrets
  azure:
    application:
      enabled: true
      allowAllUsers: true
  kafka:
    pool: nav-dev
  leaderElection: true
  env:
    - name: KTOR_ENV
      value: remote
    - name: APPLICATION_PORT
      value: "8080"
    - name: COROUTINE_THREAD_POOL_SIZE
      value: "4"
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: dev-fss.pdl.pdl-api
    - name: OP_PDFGEN_URL
      value: http://syfooppdfgen
    - name: ISDIALOGMELDING_URL
      value: http://isdialogmelding.teamsykefravr
    - name: ISDIALOGMELDING_CLIENT_ID
      value: dev-gcp.teamsykefravr.isdialogmelding
    - name: DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: DOKARKIV_SCOPE
      value: dev-fss.teamdokumenthandtering.dokarkiv
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: dev-gcp.teamsykefravr.istilgangskontroll
    - name: SEND_TO_FASTLEGE_RETRY_THRESHOLD
      value: "6"
    - name: TOGGLE_SEND_ALTINN_LPS_PLAN_TO_NAV
      value: "true"
    - name: TOGGLE_SEND_ALTINN_LPS_PLAN_TO_FASTLEGE
      value: "true"
    - name: TOGGLE_JOURNALFOR__ALTINN_LPS_PLAN
      value: "true"
    - name: MASKINPORTEN_CUSTOM_SCOPE_NAME
      value: "nav:oppfolgingsplan/lps.write"
    - name: KRR_PROXY_URL
      value: http://digdir-krr-proxy.team-rocket/rest/v1/personer
    - name: KRR_PROXY_SCOPE
      value: dev-gcp.team-rocket.digdir-krr-proxy
    - name: EREG_URL
      value: https://ereg-services-q1.dev-fss-pub.nais.io
    - name: EREG_SCOPE
      value: dev-fss.arbeidsforhold.ereg-services-q1
    - name: AAREG_URL
      value: https://aareg-services-q2.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: dev-fss.arbeidsforhold.aareg-services-nais
